# Básico sobre conversões de tipos de dados
var = "1"
print(int(var))
print(float(var))
print(bool(var))
print(str(var))
print(type(var))

# Conversões para string
bool_string = str(True)
bool_string2 = str(False)
int_string = str(5)
float_string = str(3.14159)
print("bool_string:", bool_string)
print("bool_string2:", bool_string2)
print("int_string:", int_string)
print("float_string:", float_string)
print()

# Conversões para int
string_int = int("2019")
bool_int = int(True)
bool_int2 = int(False)
float_int = int(3.14159)
string_int2 = int("101", 2)
string_int3 = int("F0A23B", 16)
print("string_int:", string_int)
print("bool_int:", bool_int)
print("bool_int2:", bool_int2)
print("float_int:", float_int)
print("string_int2:", string_int2)
print("string_int3:", string_int3)
print()

# Conversões para Float
string_float = float("3.14159")
string_float2 = float("3")
bool_float = float(True)
bool_float2 = float(False)
int_float = float(15)
print("string_float:", string_float)
print("string_float2:", string_float2)
print("bool_float:", bool_float)
print("bool_float2:", bool_float2)
print("int_float:", int_float)
print()

# Conversões para bool
string_bool = bool("Python")
string_bool2 = bool("True")
string_bool3 = bool("False")
int_bool = bool(17)
int_bool2 = bool(0)
float_bool = bool(3.14)
float_bool2 = bool(0.0)
print("string_bool:", string_bool)
print("string_bool2:", string_bool2)
print("string_bool3:", string_bool3)
print("int_bool:", int_bool)
print("int_bool2:", int_bool2)
print("float_bool:", float_bool)
print("float_bool2:", float_bool2)
print()
